project:
  type: book
  output-dir: _book

engine: knitr

book:
  title: "ggalign: Bridging the Grammar of Graphics and Complex layout"
  author: "Yun Peng"
  date: "11/24/2024"
  cover-image: cover.png
  favicon: cover.jpg
  repo-url: https://github.com/Yunuuuu/ggalign-book
  repo-branch: main
  repo-actions: ["edit", "source", "issue"]
  reader-mode: true
  chapters:
    - index.qmd

    - part: "Basics"
      chapters:
        - introduction.qmd
        - stack-layout.qmd
        - heatmap-layout.qmd
        - layout-customize.qmd
        - plot-initialize.qmd
        - annotate-observations.qmd
        - quad-layout.qmd
        - multiple-quad-layouts.qmd
        - circle-layout.qmd
        - operator.qmd
        - schemes.qmd
        - difference-with-ggplot2.qmd
        - plot-composer.qmd

    - part: "Advanced"
      chapters:
        - oncoplot.qmd

    - part: "Cases"
      chapters:
        - complete-examples.qmd

    - part: complexheatmap.qmd
      chapters:
        - complexheatmap-single-heatmap.qmd
        - complexheatmap-more-examples.qmd

bibliography: references.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"

format:
  html:
    theme: cosmo
    code-link: true
    code-annotations: hover
  pdf:
    documentclass: scrreprt
