project:
  type: book
  output-dir: _book
  execute-dir: project

engine: knitr

book:
  title: "ggalign: Bridging the Grammar of Graphics and Complex layout"
  author: "Yun Peng"
  date: today
  cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/Yunuuuu/ggalign-book
  repo-branch: main
  repo-actions: ["source", "edit", "issue"]

  code-links:
    - text: ggalign repo
      icon: code-square
      href: https://github.com/Yunuuuu/ggalign
  other-links:
    - text: ggalign reference
      icon: journal-text
      href: https://yunuuuu.github.io/ggalign
    - text: ggalign gallery
      icon: grid-1x2-fill
      href: https://yunuuuu.github.io/ggalign-gallery
    - text: ggalign manuscript
      icon: layout-text-sidebar-reverse
      href: https://www.biorxiv.org/content/10.1101/2025.02.06.636847v1

  reader-mode: true
  twitter-card: true
  chapters:
    - index.qmd

    - part: "Welcome"
      chapters: 
        - introduction.qmd
        - getting-started.qmd

    - part: "Data-free composition" # data-free.qmd
      chapters:
        - plot-composer.qmd
        - free.qmd

    - part: "Data-aware composition" # data-aware.qmd
      chapters:
        - overview.qmd
        - stack-layout.qmd
        - heatmap-layout.qmd
        - quad-layout.qmd
        - layout-customize.qmd
        - initialize-plot.qmd
        - annotate-observations.qmd
        - multiple-quad-layouts.qmd
        - circle-layout.qmd
        - operator.qmd
        - schemes.qmd
        - difference-with-ggplot2.qmd
        - oncoplot.qmd

bibliography: references.bib

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>"

format:
  html:
    theme:
      light: [cosmo, scss/light.scss]
      dark: [cosmo, scss/dark.scss]
    respect-user-color-scheme: true
    code-link: true
    code-annotations: hover
    mermaid:
      theme: default
  pdf:
    documentclass: scrreprt
