on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  # to be able to trigger a manual build
  workflow_dispatch:
  schedule:
    # run every day at 11 PM
    - cron: '0 23 * * *'

name: Render and deploy Book to Github Page

# https://github.com/r-lib/actions/tree/v2/examples#render-rmarkdown
# https://github.com/quarto-dev/quarto-actions

env:
  isExtPR: ${{ github.event.pull_request.head.repo.fork == true }}
  RUST_BACKTRACE: 1

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tinytex: true

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2

      # The Check Chromium step appears necessary to avoid a crash/hang when rendering PDFs
      # https://github.com/quarto-dev/quarto-actions/issues/45#issuecomment-1562599451
      - name: Check chromium
        if: ${{ runner.os == 'Linux' }}
        run: |
          CHROMIUM_PATH=$(which chromium-browser)
          if [ -x "$CHROMIUM_PATH" ]; then
            echo $CHROMIUM_PATH
            "$CHROMIUM_PATH" --headless --no-sandbox --disable-gpu --renderer-process-limit=1 https://www.chromestatus.com || echo "Headless run failed"
          else
            echo "No Chromium executable found"
          fi
        shell: bash

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        env:
          QUARTO_PROFILE: preview

      - name: Upload Quarto artifacts
        if: ${{ github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_book"

      - name: Deploy to GitHub Pages
        if: github.event_name != 'pull_request'
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          render: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
